var styleElement = document.createElement('style');
styleElement.textContent = "@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Nanum+Gothic+Coding&family=Yarndings+12&display=swap');";
document.head.appendChild(styleElement);

var metaCharset = document.createElement('meta');
metaCharset.setAttribute('charset', 'UTF-8');
var metaXUACompatible = document.createElement('meta');
metaXUACompatible.setAttribute('http-equiv', 'X-UA-Compatible');
metaXUACompatible.setAttribute('content', 'IE=Edge');
var metaViewport = document.createElement('meta');
metaViewport.setAttribute('name', 'viewport');
metaViewport.setAttribute('content', 'width=device-width, initial-scale=1');
var metaAuthor = document.createElement('meta');
metaAuthor.setAttribute('name', 'author');
metaAuthor.setAttribute('content', 'Crystal Person');
var metaOGTitle = document.createElement('meta');
metaOGTitle.setAttribute('name', 'og:title');
metaOGTitle.setAttribute('content', 'Hi, Im Crystal Person');
var metaOGDescription = document.createElement('meta');
metaOGDescription.setAttribute('name', 'og:description');
metaOGDescription.setAttribute('content', 'Know About Me');
var metaOGImage = document.createElement('meta');
metaOGImage.setAttribute('name', 'og:image');
metaOGImage.setAttribute('content', 'https://firebasestorage.googleapis.com/v0/b/eternal-galaxy-413919.appspot.com/o/New%20Project%20%5B1ED2954%5D.png?alt=media&token=38e96933-0b50-4f3e-b792-c6f32cfbc744');
var metaThemeColor = document.createElement('meta');
metaThemeColor.setAttribute('name', 'theme-color');
metaThemeColor.setAttribute('content', '#CFD8DC');
var metaGoogleSiteVerification = document.createElement('meta');
metaGoogleSiteVerification.setAttribute('name', 'google-site-verification');
metaGoogleSiteVerification.setAttribute('content', 'J20YkdBYbFS0_YZdIu9Z-sKGKzYZfqOFFkQ0numjLq0');
var metaDescription = document.createElement('meta');
metaDescription.setAttribute('name', 'description');
metaDescription.setAttribute('content', 'Free Fire is a multiplayer battle royale mobile game, developed and published by Garena for Android and iOS. Battle in Style and be the last survivor!');
var metaKeywords = document.createElement('meta');
metaKeywords.setAttribute('name', 'keywords');
metaKeywords.setAttribute('content', 'survival, last survivor, battle royale, free mobile game, garena game, craftland, ugc, ff craftland, jinxx66, jinxx6_6, jinxx, craftland tutorial, free fire craftland');
var linkFavicon = document.createElement('link');
linkFavicon.setAttribute('rel', 'icon');
linkFavicon.setAttribute('type', 'image/x-icon');
linkFavicon.setAttribute('href', 'https://firebasestorage.googleapis.com/v0/b/eternal-galaxy-413919.appspot.com/o/text-1712281672280.png?alt=media&token=dd31091b-78d0-4b1e-9ec6-b6f45f8d935f');
var title = document.createElement('title');
title.textContent = 'About';
document.head.appendChild(metaCharset);
document.head.appendChild(metaXUACompatible);
document.head.appendChild(metaViewport);
document.head.appendChild(metaAuthor);
document.head.appendChild(metaOGTitle);
document.head.appendChild(metaOGDescription);
document.head.appendChild(metaOGImage);
document.head.appendChild(metaThemeColor);
document.head.appendChild(metaGoogleSiteVerification);
document.head.appendChild(metaDescription);
document.head.appendChild(metaKeywords);
document.head.appendChild(linkFavicon);
document.head.appendChild(title);